### ISSUE TITLE
Load Error

### ISSUE THREAD

**Issue by Absinthze** [MackinationsAi/SD3#1]
Tried a fresh install, and both Firefox and Chrome.  Getting this error on load in windows.

File "D:\SD3\SD3.py", line 51
      st.image("static/SD3_webui_logo_image.png", use_column_width=True)
  ^
SyntaxError: invalid non-printable character U+00A0

**Comment by MackinationsAi** [comment]
This was an update to get the title banner to adjust to the device that the end user wants to use (which was more geared towards the huggingface space if you wanted to use it to generate on your mobile device). I just updated the code and tested it out with a fresh install & the error went away, I also updated both the run_SD3.bat & run_SD3.sh to include the git pull & tested them both & based on the new update the error went away as well. So you can either do a fresh reinstall or just download the new run_SD3.bat or run_SD3.sh depending on what OS you are using & you should be good to go now!

**Comment by Absinthze** [comment]
Hi MAI,  I dont know how to message you outside of Github.  I've clone the space on Hugginface, does the output save somewhere on my local drive?  I have a presentation tomorrow and wanted to use your app somehow to generate images using my API and have them automatically save on the local machine.  Any suggestions without installing it from github locally?  Thanks,
Appreciate your hard work.

**Comment by MackinationsAi** [comment]
The huggingface space requires you to pay for storage, so no there is no way to have it save to you folder automatically. However, the download is really easy for both Windows and MacOS if you use this github repo & it doesn't take up any space. The code for this github repo automatically downloads the images you generate to a folder in the directory & displays all of the generations in a gallery page in the WebUI. I updated the install instructions to make it extremely easy to set up.
